version: '3.9'

services:
  smart-tutor-migration:
    build:
      dockerfile: Migrations_Dockerfile
      context: .
      target: execute-migration
    networks:
      - servers
    environment:
      DATABASE_HOST: database
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: super
      DATABASE_SCHEMA: explorer-v1

  database:
    image: postgres
    container_name: postgres_container
    restart: always
    networks:
      - servers
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_DB: explorer-v1
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
    name: server-database

networks:
  servers:
    name: servers
    driver: bridge
    external: true