version: "3"

services:
  # Loki:
  loki:
    image: grafana/loki:main-5206e3a
    networks:
      - monitoring
    restart: always  # Dodajemo opciju restart: always za automatsko restartovanje

  # Grafana:
  grafana:
    image: grafana/grafana:8.5.3
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8881/render
      GF_RENDER_CALL_BACK_URL: http://grafana:3880/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - monitoring
    restart: always  # Dodajemo opciju restart: always za automatsko restartovanje

  # Grafana renderer:
  renderer:
    image: grafana/grafana-image-renderer:3.4.2
    environment:
      ENABLE_METRICS: "true"
    networks:
      - monitoring
    restart: always  # Dodajemo opciju restart: always za automatsko restartovanje

  # Fluent Bit:
  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:main-5206e3a-amd64
    environment:
      LOKI_URL: http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - monitoring
    restart: always  # Dodajemo opciju restart: always za automatsko restartovanje

# Networks:
networks:
  monitoring:
    name: monitoring
    driver: bridge
