version: "3.7"

x-logging: &fluent-bit
  driver: fluentd
  options:
    fluentd-address: 0.0.0.0:24224
    tag: docker.{{.Name}}

services:
  tours-module:
    build:
      context: ./
      dockerfile: module_tour/Dockerfile
    image: toursmodule
    container_name: tours_module
    restart: always
    logging: *fluent-bit
    networks:
      - servers
      - monitoring
    ports:
      - "${TOURS_APP_PORT}:${TOURS_APP_PORT}"
    environment:
      TOURS_DB_HOST: ${TOURS_DB_HOST}
      TOURS_DB_USERNAME: ${TOURS_DB_USERNAME}
      TOURS_DB_PASSWORD: ${TOURS_DB_PASSWORD}
      TOURS_DB: ${TOURS_DB}
      TOURS_DB_PORT: ${TOURS_DB_PORT}
      TOURS_SCHEMA: ${TOURS_SCHEMA}
      TOURS_APP_PORT: ${TOURS_APP_PORT}
      FLUENTD_TAG: docker.{{.Name}}
    depends_on:
      - database

  stakeholders-module:
    build:
      context: ./
      dockerfile: module_stakeholders/Dockerfile
    image: stakeholdersmodule
    container_name: stakeholders_module
    logging: *fluent-bit
    restart: always
    networks:
      - servers
      - monitoring 
    ports:
      - "${STAKEHOLDERS_APP_PORT}:${STAKEHOLDERS_APP_PORT}"
    environment:
      STAKEHOLDERS_DB_HOST: ${STAKEHOLDERS_DB_HOST}
      STAKEHOLDERS_DB_USERNAME: ${STAKEHOLDERS_DB_USERNAME}
      STAKEHOLDERS_DB_PASSWORD: ${STAKEHOLDERS_DB_PASSWORD}
      STAKEHOLDERS_DB: ${STAKEHOLDERS_DB}
      STAKEHOLDERS_DB_PORT: ${STAKEHOLDERS_DB_PORT}
      STAKEHOLDERS_SCHEMA: ${STAKEHOLDERS_SCHEMA}
      STAKEHOLDERS_APP_PORT: ${STAKEHOLDERS_APP_PORT}
      FLUENTD_TAG: docker.{{.Name}}
    depends_on:
      - database

  followers-module:
    build:
      context: ./module_follower
      dockerfile: Dockerfile
    image: followersmodule
    container_name: followers_module
    logging: *fluent-bit
    restart: always
    networks:
      - servers
      - monitoring
    ports:
      - "${FOLLOWERS_APP_PORT}:${FOLLOWERS_APP_PORT}"
    environment:
      NEO4J_PORT: ${NEO4J_PORT}
      NEO4J_PORT_BOLT: ${NEO4J_PORT_BOLT}
      NEO4J_DB_URI: ${NEO4J_DB_URI}
      FLUENTD_TAG: docker.{{.Name}}
    depends_on:
      - database

  explorer:
    build:
      dockerfile: tourism_monolith/Dockerfile
      context: .
      target: final
    image: explorer
    container_name: explorer
    logging: *fluent-bit
    restart: on-failure
    networks:
      - servers
      - monitoring
    ports:
      - "44333:443"
      - "1234:80"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorer-v1
      FLUENTD_TAG: docker.{{.Name}}
      TOURS_APP_PORT: ${TOURS_APP_PORT}
      ASPNETCORE_URLS: https://+:443;http://+:80
    depends_on:
      - database
  
  database:
    image: postgres
    container_name: postgres_container
    restart: always
    logging: *fluent-bit
    networks:
      - servers
      - monitoring
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_DB: explorer-v1
      FLUENTD_TAG: docker.{{.Name}}
    volumes:
      - database-data:/var/lib/postgresql/data
    
  mongo-db:
    image: mongo
    container_name: mongo-db
    logging: *fluent-bit
    restart: always
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    environment:
      MONGO_INITDB_DATABASE: mongoDemo
    networks:
      - servers
      - monitoring

  neo4j-db:
    image: neo4j
    container_name: neo4j-db
    logging: *fluent-bit
    ports:
    - "${NEO4J_PORT}:${NEO4J_PORT}"
    - "${NEO4J_PORT_BOLT}:${NEO4J_PORT_BOLT}"
    environment:
      NEO4J_AUTH: none
      FLUENTD_TAG: docker.{{.Name}}
    networks:
    - servers
    - monitoring
  
  blogs-module:
    build: 
      context: ./
      dockerfile: module_blog/Dockerfile
    image: blogsmodule
    container_name: blogs_module
    logging: *fluent-bit
    restart: always
    networks:
      - servers
      - monitoring
    ports:
      - "${BLOGS_APP_PORT}:${BLOGS_APP_PORT}"
    environment:
      BLOGS_DB_HOST: ${BLOGS_DB_HOST}
      BLOGS_DB_USERNAME: ${BLOGS_DB_USERNAME}
      BLOGS_DB_PASSWORD: ${BLOGS_DB_PASSWORD}
      BLOGS_DB: ${BLOGS_DB}
      BLOGS_DB_PORT: ${BLOGS_DB_PORT}
      BLOGS_SCHEMA: ${BLOGS_SCHEMA}
      BLOGS_APP_PORT: ${BLOGS_APP_PORT}
      FLUENTD_TAG: docker.{{.Name}}
    depends_on:
      - mongo-db
      - database

  api-gateway:
    build: 
      context: ./
      dockerfile: api_gateway/Dockerfile
    image: api_gateway
    container_name: api-gateway
    logging: *fluent-bit
    restart: always
    networks:
      - servers
      - monitoring
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    depends_on:
      - mongo-db
      - database

volumes:
  database-data:
    name: server-database

networks:
  servers:
    name: servers
    driver: bridge
  monitoring:
    external: true