// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: proto/tour_service.proto

package tour

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TourProgressServiceClient is the client API for TourProgressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourProgressServiceClient interface {
	CreateTourProgress(ctx context.Context, in *TourProgress, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetAllTourProgress(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MultiTourProgressResponse, error)
	GetTourProgressById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*TourProgressResponse, error)
	UpdateTourProgress(ctx context.Context, in *TourProgress, opts ...grpc.CallOption) (*EmptyResponse, error)
	DeleteTourProgress(ctx context.Context, in *Id, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type tourProgressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourProgressServiceClient(cc grpc.ClientConnInterface) TourProgressServiceClient {
	return &tourProgressServiceClient{cc}
}

func (c *tourProgressServiceClient) CreateTourProgress(ctx context.Context, in *TourProgress, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tour.TourProgressService/CreateTourProgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourProgressServiceClient) GetAllTourProgress(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MultiTourProgressResponse, error) {
	out := new(MultiTourProgressResponse)
	err := c.cc.Invoke(ctx, "/tour.TourProgressService/GetAllTourProgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourProgressServiceClient) GetTourProgressById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*TourProgressResponse, error) {
	out := new(TourProgressResponse)
	err := c.cc.Invoke(ctx, "/tour.TourProgressService/GetTourProgressById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourProgressServiceClient) UpdateTourProgress(ctx context.Context, in *TourProgress, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tour.TourProgressService/UpdateTourProgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourProgressServiceClient) DeleteTourProgress(ctx context.Context, in *Id, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tour.TourProgressService/DeleteTourProgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourProgressServiceServer is the server API for TourProgressService service.
// All implementations should embed UnimplementedTourProgressServiceServer
// for forward compatibility
type TourProgressServiceServer interface {
	CreateTourProgress(context.Context, *TourProgress) (*EmptyResponse, error)
	GetAllTourProgress(context.Context, *Empty) (*MultiTourProgressResponse, error)
	GetTourProgressById(context.Context, *Id) (*TourProgressResponse, error)
	UpdateTourProgress(context.Context, *TourProgress) (*EmptyResponse, error)
	DeleteTourProgress(context.Context, *Id) (*EmptyResponse, error)
}

// UnimplementedTourProgressServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTourProgressServiceServer struct {
}

func (UnimplementedTourProgressServiceServer) CreateTourProgress(context.Context, *TourProgress) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTourProgress not implemented")
}
func (UnimplementedTourProgressServiceServer) GetAllTourProgress(context.Context, *Empty) (*MultiTourProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTourProgress not implemented")
}
func (UnimplementedTourProgressServiceServer) GetTourProgressById(context.Context, *Id) (*TourProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTourProgressById not implemented")
}
func (UnimplementedTourProgressServiceServer) UpdateTourProgress(context.Context, *TourProgress) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTourProgress not implemented")
}
func (UnimplementedTourProgressServiceServer) DeleteTourProgress(context.Context, *Id) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTourProgress not implemented")
}

// UnsafeTourProgressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourProgressServiceServer will
// result in compilation errors.
type UnsafeTourProgressServiceServer interface {
	mustEmbedUnimplementedTourProgressServiceServer()
}

func RegisterTourProgressServiceServer(s grpc.ServiceRegistrar, srv TourProgressServiceServer) {
	s.RegisterService(&TourProgressService_ServiceDesc, srv)
}

func _TourProgressService_CreateTourProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourProgress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourProgressServiceServer).CreateTourProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TourProgressService/CreateTourProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourProgressServiceServer).CreateTourProgress(ctx, req.(*TourProgress))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourProgressService_GetAllTourProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourProgressServiceServer).GetAllTourProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TourProgressService/GetAllTourProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourProgressServiceServer).GetAllTourProgress(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourProgressService_GetTourProgressById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourProgressServiceServer).GetTourProgressById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TourProgressService/GetTourProgressById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourProgressServiceServer).GetTourProgressById(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourProgressService_UpdateTourProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourProgress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourProgressServiceServer).UpdateTourProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TourProgressService/UpdateTourProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourProgressServiceServer).UpdateTourProgress(ctx, req.(*TourProgress))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourProgressService_DeleteTourProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourProgressServiceServer).DeleteTourProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TourProgressService/DeleteTourProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourProgressServiceServer).DeleteTourProgress(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

// TourProgressService_ServiceDesc is the grpc.ServiceDesc for TourProgressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourProgressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tour.TourProgressService",
	HandlerType: (*TourProgressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTourProgress",
			Handler:    _TourProgressService_CreateTourProgress_Handler,
		},
		{
			MethodName: "GetAllTourProgress",
			Handler:    _TourProgressService_GetAllTourProgress_Handler,
		},
		{
			MethodName: "GetTourProgressById",
			Handler:    _TourProgressService_GetTourProgressById_Handler,
		},
		{
			MethodName: "UpdateTourProgress",
			Handler:    _TourProgressService_UpdateTourProgress_Handler,
		},
		{
			MethodName: "DeleteTourProgress",
			Handler:    _TourProgressService_DeleteTourProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tour_service.proto",
}

// TouristPositionServiceClient is the client API for TouristPositionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TouristPositionServiceClient interface {
	CreateTouristPosition(ctx context.Context, in *TouristPosition, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetTouristPositionById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*TouristPositionResponse, error)
	GetTouristPositionByUser(ctx context.Context, in *Id, opts ...grpc.CallOption) (*TouristPositionResponse, error)
	UpdateTouristPosition(ctx context.Context, in *TouristPosition, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type touristPositionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTouristPositionServiceClient(cc grpc.ClientConnInterface) TouristPositionServiceClient {
	return &touristPositionServiceClient{cc}
}

func (c *touristPositionServiceClient) CreateTouristPosition(ctx context.Context, in *TouristPosition, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tour.TouristPositionService/CreateTouristPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *touristPositionServiceClient) GetTouristPositionById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*TouristPositionResponse, error) {
	out := new(TouristPositionResponse)
	err := c.cc.Invoke(ctx, "/tour.TouristPositionService/GetTouristPositionById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *touristPositionServiceClient) GetTouristPositionByUser(ctx context.Context, in *Id, opts ...grpc.CallOption) (*TouristPositionResponse, error) {
	out := new(TouristPositionResponse)
	err := c.cc.Invoke(ctx, "/tour.TouristPositionService/GetTouristPositionByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *touristPositionServiceClient) UpdateTouristPosition(ctx context.Context, in *TouristPosition, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tour.TouristPositionService/UpdateTouristPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TouristPositionServiceServer is the server API for TouristPositionService service.
// All implementations should embed UnimplementedTouristPositionServiceServer
// for forward compatibility
type TouristPositionServiceServer interface {
	CreateTouristPosition(context.Context, *TouristPosition) (*EmptyResponse, error)
	GetTouristPositionById(context.Context, *Id) (*TouristPositionResponse, error)
	GetTouristPositionByUser(context.Context, *Id) (*TouristPositionResponse, error)
	UpdateTouristPosition(context.Context, *TouristPosition) (*EmptyResponse, error)
}

// UnimplementedTouristPositionServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTouristPositionServiceServer struct {
}

func (UnimplementedTouristPositionServiceServer) CreateTouristPosition(context.Context, *TouristPosition) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTouristPosition not implemented")
}
func (UnimplementedTouristPositionServiceServer) GetTouristPositionById(context.Context, *Id) (*TouristPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTouristPositionById not implemented")
}
func (UnimplementedTouristPositionServiceServer) GetTouristPositionByUser(context.Context, *Id) (*TouristPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTouristPositionByUser not implemented")
}
func (UnimplementedTouristPositionServiceServer) UpdateTouristPosition(context.Context, *TouristPosition) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTouristPosition not implemented")
}

// UnsafeTouristPositionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TouristPositionServiceServer will
// result in compilation errors.
type UnsafeTouristPositionServiceServer interface {
	mustEmbedUnimplementedTouristPositionServiceServer()
}

func RegisterTouristPositionServiceServer(s grpc.ServiceRegistrar, srv TouristPositionServiceServer) {
	s.RegisterService(&TouristPositionService_ServiceDesc, srv)
}

func _TouristPositionService_CreateTouristPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouristPosition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TouristPositionServiceServer).CreateTouristPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TouristPositionService/CreateTouristPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TouristPositionServiceServer).CreateTouristPosition(ctx, req.(*TouristPosition))
	}
	return interceptor(ctx, in, info, handler)
}

func _TouristPositionService_GetTouristPositionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TouristPositionServiceServer).GetTouristPositionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TouristPositionService/GetTouristPositionById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TouristPositionServiceServer).GetTouristPositionById(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _TouristPositionService_GetTouristPositionByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TouristPositionServiceServer).GetTouristPositionByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TouristPositionService/GetTouristPositionByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TouristPositionServiceServer).GetTouristPositionByUser(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _TouristPositionService_UpdateTouristPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouristPosition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TouristPositionServiceServer).UpdateTouristPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TouristPositionService/UpdateTouristPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TouristPositionServiceServer).UpdateTouristPosition(ctx, req.(*TouristPosition))
	}
	return interceptor(ctx, in, info, handler)
}

// TouristPositionService_ServiceDesc is the grpc.ServiceDesc for TouristPositionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TouristPositionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tour.TouristPositionService",
	HandlerType: (*TouristPositionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTouristPosition",
			Handler:    _TouristPositionService_CreateTouristPosition_Handler,
		},
		{
			MethodName: "GetTouristPositionById",
			Handler:    _TouristPositionService_GetTouristPositionById_Handler,
		},
		{
			MethodName: "GetTouristPositionByUser",
			Handler:    _TouristPositionService_GetTouristPositionByUser_Handler,
		},
		{
			MethodName: "UpdateTouristPosition",
			Handler:    _TouristPositionService_UpdateTouristPosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tour_service.proto",
}

// KeypointServiceClient is the client API for KeypointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeypointServiceClient interface {
	CreateKeypoint(ctx context.Context, in *Keypoint, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetKeypointsByTourId(ctx context.Context, in *Id, opts ...grpc.CallOption) (*MultiKeypointResponse, error)
	UpdateKeypoint(ctx context.Context, in *Keypoint, opts ...grpc.CallOption) (*EmptyResponse, error)
	DeleteKeypoint(ctx context.Context, in *Id, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type keypointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeypointServiceClient(cc grpc.ClientConnInterface) KeypointServiceClient {
	return &keypointServiceClient{cc}
}

func (c *keypointServiceClient) CreateKeypoint(ctx context.Context, in *Keypoint, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tour.KeypointService/CreateKeypoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keypointServiceClient) GetKeypointsByTourId(ctx context.Context, in *Id, opts ...grpc.CallOption) (*MultiKeypointResponse, error) {
	out := new(MultiKeypointResponse)
	err := c.cc.Invoke(ctx, "/tour.KeypointService/GetKeypointsByTourId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keypointServiceClient) UpdateKeypoint(ctx context.Context, in *Keypoint, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tour.KeypointService/UpdateKeypoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keypointServiceClient) DeleteKeypoint(ctx context.Context, in *Id, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tour.KeypointService/DeleteKeypoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeypointServiceServer is the server API for KeypointService service.
// All implementations should embed UnimplementedKeypointServiceServer
// for forward compatibility
type KeypointServiceServer interface {
	CreateKeypoint(context.Context, *Keypoint) (*EmptyResponse, error)
	GetKeypointsByTourId(context.Context, *Id) (*MultiKeypointResponse, error)
	UpdateKeypoint(context.Context, *Keypoint) (*EmptyResponse, error)
	DeleteKeypoint(context.Context, *Id) (*EmptyResponse, error)
}

// UnimplementedKeypointServiceServer should be embedded to have forward compatible implementations.
type UnimplementedKeypointServiceServer struct {
}

func (UnimplementedKeypointServiceServer) CreateKeypoint(context.Context, *Keypoint) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKeypoint not implemented")
}
func (UnimplementedKeypointServiceServer) GetKeypointsByTourId(context.Context, *Id) (*MultiKeypointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeypointsByTourId not implemented")
}
func (UnimplementedKeypointServiceServer) UpdateKeypoint(context.Context, *Keypoint) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKeypoint not implemented")
}
func (UnimplementedKeypointServiceServer) DeleteKeypoint(context.Context, *Id) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKeypoint not implemented")
}

// UnsafeKeypointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeypointServiceServer will
// result in compilation errors.
type UnsafeKeypointServiceServer interface {
	mustEmbedUnimplementedKeypointServiceServer()
}

func RegisterKeypointServiceServer(s grpc.ServiceRegistrar, srv KeypointServiceServer) {
	s.RegisterService(&KeypointService_ServiceDesc, srv)
}

func _KeypointService_CreateKeypoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Keypoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeypointServiceServer).CreateKeypoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.KeypointService/CreateKeypoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeypointServiceServer).CreateKeypoint(ctx, req.(*Keypoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeypointService_GetKeypointsByTourId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeypointServiceServer).GetKeypointsByTourId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.KeypointService/GetKeypointsByTourId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeypointServiceServer).GetKeypointsByTourId(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeypointService_UpdateKeypoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Keypoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeypointServiceServer).UpdateKeypoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.KeypointService/UpdateKeypoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeypointServiceServer).UpdateKeypoint(ctx, req.(*Keypoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeypointService_DeleteKeypoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeypointServiceServer).DeleteKeypoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.KeypointService/DeleteKeypoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeypointServiceServer).DeleteKeypoint(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

// KeypointService_ServiceDesc is the grpc.ServiceDesc for KeypointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeypointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tour.KeypointService",
	HandlerType: (*KeypointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKeypoint",
			Handler:    _KeypointService_CreateKeypoint_Handler,
		},
		{
			MethodName: "GetKeypointsByTourId",
			Handler:    _KeypointService_GetKeypointsByTourId_Handler,
		},
		{
			MethodName: "UpdateKeypoint",
			Handler:    _KeypointService_UpdateKeypoint_Handler,
		},
		{
			MethodName: "DeleteKeypoint",
			Handler:    _KeypointService_DeleteKeypoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tour_service.proto",
}

// TourServiceClient is the client API for TourService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourServiceClient interface {
	CreateTour(ctx context.Context, in *Tour, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetTourById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*TourResponse, error)
	GetTourByStatus(ctx context.Context, in *Status, opts ...grpc.CallOption) (*MultiTourResponse, error)
	GetTourByAuthor(ctx context.Context, in *Id, opts ...grpc.CallOption) (*MultiTourResponse, error)
	UpdateTour(ctx context.Context, in *Tour, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetAllTours(ctx context.Context, in *EmptyResponse, opts ...grpc.CallOption) (*MultiTourResponse, error)
}

type tourServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourServiceClient(cc grpc.ClientConnInterface) TourServiceClient {
	return &tourServiceClient{cc}
}

func (c *tourServiceClient) CreateTour(ctx context.Context, in *Tour, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tour.TourService/CreateTour", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetTourById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*TourResponse, error) {
	out := new(TourResponse)
	err := c.cc.Invoke(ctx, "/tour.TourService/GetTourById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetTourByStatus(ctx context.Context, in *Status, opts ...grpc.CallOption) (*MultiTourResponse, error) {
	out := new(MultiTourResponse)
	err := c.cc.Invoke(ctx, "/tour.TourService/GetTourByStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetTourByAuthor(ctx context.Context, in *Id, opts ...grpc.CallOption) (*MultiTourResponse, error) {
	out := new(MultiTourResponse)
	err := c.cc.Invoke(ctx, "/tour.TourService/GetTourByAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) UpdateTour(ctx context.Context, in *Tour, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tour.TourService/UpdateTour", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetAllTours(ctx context.Context, in *EmptyResponse, opts ...grpc.CallOption) (*MultiTourResponse, error) {
	out := new(MultiTourResponse)
	err := c.cc.Invoke(ctx, "/tour.TourService/GetAllTours", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourServiceServer is the server API for TourService service.
// All implementations should embed UnimplementedTourServiceServer
// for forward compatibility
type TourServiceServer interface {
	CreateTour(context.Context, *Tour) (*EmptyResponse, error)
	GetTourById(context.Context, *Id) (*TourResponse, error)
	GetTourByStatus(context.Context, *Status) (*MultiTourResponse, error)
	GetTourByAuthor(context.Context, *Id) (*MultiTourResponse, error)
	UpdateTour(context.Context, *Tour) (*EmptyResponse, error)
	GetAllTours(context.Context, *EmptyResponse) (*MultiTourResponse, error)
}

// UnimplementedTourServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTourServiceServer struct {
}

func (UnimplementedTourServiceServer) CreateTour(context.Context, *Tour) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTour not implemented")
}
func (UnimplementedTourServiceServer) GetTourById(context.Context, *Id) (*TourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTourById not implemented")
}
func (UnimplementedTourServiceServer) GetTourByStatus(context.Context, *Status) (*MultiTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTourByStatus not implemented")
}
func (UnimplementedTourServiceServer) GetTourByAuthor(context.Context, *Id) (*MultiTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTourByAuthor not implemented")
}
func (UnimplementedTourServiceServer) UpdateTour(context.Context, *Tour) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTour not implemented")
}
func (UnimplementedTourServiceServer) GetAllTours(context.Context, *EmptyResponse) (*MultiTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTours not implemented")
}

// UnsafeTourServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourServiceServer will
// result in compilation errors.
type UnsafeTourServiceServer interface {
	mustEmbedUnimplementedTourServiceServer()
}

func RegisterTourServiceServer(s grpc.ServiceRegistrar, srv TourServiceServer) {
	s.RegisterService(&TourService_ServiceDesc, srv)
}

func _TourService_CreateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tour)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).CreateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TourService/CreateTour",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).CreateTour(ctx, req.(*Tour))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetTourById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetTourById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TourService/GetTourById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetTourById(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetTourByStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Status)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetTourByStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TourService/GetTourByStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetTourByStatus(ctx, req.(*Status))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetTourByAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetTourByAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TourService/GetTourByAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetTourByAuthor(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_UpdateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tour)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).UpdateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TourService/UpdateTour",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).UpdateTour(ctx, req.(*Tour))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetAllTours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetAllTours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TourService/GetAllTours",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetAllTours(ctx, req.(*EmptyResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// TourService_ServiceDesc is the grpc.ServiceDesc for TourService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tour.TourService",
	HandlerType: (*TourServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTour",
			Handler:    _TourService_CreateTour_Handler,
		},
		{
			MethodName: "GetTourById",
			Handler:    _TourService_GetTourById_Handler,
		},
		{
			MethodName: "GetTourByStatus",
			Handler:    _TourService_GetTourByStatus_Handler,
		},
		{
			MethodName: "GetTourByAuthor",
			Handler:    _TourService_GetTourByAuthor_Handler,
		},
		{
			MethodName: "UpdateTour",
			Handler:    _TourService_UpdateTour_Handler,
		},
		{
			MethodName: "GetAllTours",
			Handler:    _TourService_GetAllTours_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tour_service.proto",
}

// TourEquipmentServiceClient is the client API for TourEquipmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourEquipmentServiceClient interface {
	CreateTourEquipment(ctx context.Context, in *TourEquipment, opts ...grpc.CallOption) (*EmptyResponse, error)
	GetAllTourEquipment(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MultiTourEquipmentResponse, error)
	DeleteTourEquipment(ctx context.Context, in *TourEquipment, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type tourEquipmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourEquipmentServiceClient(cc grpc.ClientConnInterface) TourEquipmentServiceClient {
	return &tourEquipmentServiceClient{cc}
}

func (c *tourEquipmentServiceClient) CreateTourEquipment(ctx context.Context, in *TourEquipment, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tour.TourEquipmentService/CreateTourEquipment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourEquipmentServiceClient) GetAllTourEquipment(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MultiTourEquipmentResponse, error) {
	out := new(MultiTourEquipmentResponse)
	err := c.cc.Invoke(ctx, "/tour.TourEquipmentService/GetAllTourEquipment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourEquipmentServiceClient) DeleteTourEquipment(ctx context.Context, in *TourEquipment, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tour.TourEquipmentService/DeleteTourEquipment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourEquipmentServiceServer is the server API for TourEquipmentService service.
// All implementations should embed UnimplementedTourEquipmentServiceServer
// for forward compatibility
type TourEquipmentServiceServer interface {
	CreateTourEquipment(context.Context, *TourEquipment) (*EmptyResponse, error)
	GetAllTourEquipment(context.Context, *Empty) (*MultiTourEquipmentResponse, error)
	DeleteTourEquipment(context.Context, *TourEquipment) (*EmptyResponse, error)
}

// UnimplementedTourEquipmentServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTourEquipmentServiceServer struct {
}

func (UnimplementedTourEquipmentServiceServer) CreateTourEquipment(context.Context, *TourEquipment) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTourEquipment not implemented")
}
func (UnimplementedTourEquipmentServiceServer) GetAllTourEquipment(context.Context, *Empty) (*MultiTourEquipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTourEquipment not implemented")
}
func (UnimplementedTourEquipmentServiceServer) DeleteTourEquipment(context.Context, *TourEquipment) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTourEquipment not implemented")
}

// UnsafeTourEquipmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourEquipmentServiceServer will
// result in compilation errors.
type UnsafeTourEquipmentServiceServer interface {
	mustEmbedUnimplementedTourEquipmentServiceServer()
}

func RegisterTourEquipmentServiceServer(s grpc.ServiceRegistrar, srv TourEquipmentServiceServer) {
	s.RegisterService(&TourEquipmentService_ServiceDesc, srv)
}

func _TourEquipmentService_CreateTourEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourEquipment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourEquipmentServiceServer).CreateTourEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TourEquipmentService/CreateTourEquipment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourEquipmentServiceServer).CreateTourEquipment(ctx, req.(*TourEquipment))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourEquipmentService_GetAllTourEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourEquipmentServiceServer).GetAllTourEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TourEquipmentService/GetAllTourEquipment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourEquipmentServiceServer).GetAllTourEquipment(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourEquipmentService_DeleteTourEquipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourEquipment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourEquipmentServiceServer).DeleteTourEquipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour.TourEquipmentService/DeleteTourEquipment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourEquipmentServiceServer).DeleteTourEquipment(ctx, req.(*TourEquipment))
	}
	return interceptor(ctx, in, info, handler)
}

// TourEquipmentService_ServiceDesc is the grpc.ServiceDesc for TourEquipmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourEquipmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tour.TourEquipmentService",
	HandlerType: (*TourEquipmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTourEquipment",
			Handler:    _TourEquipmentService_CreateTourEquipment_Handler,
		},
		{
			MethodName: "GetAllTourEquipment",
			Handler:    _TourEquipmentService_GetAllTourEquipment_Handler,
		},
		{
			MethodName: "DeleteTourEquipment",
			Handler:    _TourEquipmentService_DeleteTourEquipment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tour_service.proto",
}
